### ISSUE TITLE
Ghcid not working properly

### ISSUE THREAD

**Issue by sproott** [fjvallarino/monomer#88] opened 2022-02-22 12:39 UTC
I tried using `ghcid` for development. After saving a file, the original app window stays open and another one opens and the app cannot be stopped normally, I have to Ctrl+C the `ghcid` command itself. So, I basically cannot use `ghcid` for development. Screenshots:

- First open of the app

![image](https://user-images.githubusercontent.com/46423131/155133926-33927156-cb8c-49fb-8a0f-07376a15550e.png)

- After saving a file

![image](https://user-images.githubusercontent.com/46423131/155134023-e9e342b2-f196-4635-9658-a1bc5af32c41.png)

**Comment by fjvallarino** [comment] 2022-02-22 12:47
Hi @sproott!

Yes, that's the expected behavior: you have to close the previous window before making changes; otherwise, both instances will run alongside. It does not work as in a Lisp where you can dynamically replace code; it just launches a new application instance.

The main reason for using `ghcid` is that the development cycle is much faster than compiling and running.

**Comment by sproott** [comment] 2022-02-22 13:05
So I suppose the previous window cannot be closed automatically? Of course I expected it to open a new window, but the current behaviour seemed broken to me.

**Comment by fjvallarino** [comment] 2022-02-22 13:23
It might be possible, but it can get complicated. The existing and new application instances would need to communicate somehow in order to have the old one shut down itself, probably using a socket or similar. Using a socket may cause issues with open ports/etc, so ideally something else can be used.

I'll think about it.

**Comment by sproott** [comment] 2022-02-22 13:26
I would just have ghcid signal SIGTERM to the original application, of course I have no idea if something like that can be done in a ghcid config.

**Comment by fjvallarino** [comment] 2022-02-22 13:31
The problem is everything runs inside a `ghci` instance (`ghcid` uses it under the hood). Using SIGTERM would kill the whole process, including the new application instance.

**Comment by sproott** [comment] 2022-02-23 09:19
Today I've found this library: https://hackage.haskell.org/package/rapid which can be used to restart/update parts of the application for hot reloading. Could this work?

**Comment by sproott** [comment] 2022-02-23 11:14
Related issue: https://github.com/ndmitchell/ghcid/issues/191

**Comment by fjvallarino** [comment] 2022-02-25 18:13
Fixing the issue through `ghcid` would be ideal. I'll take a look; it is a nice feature to have.

I think the implemented solution should be part of [`monomer-starter`](https://github.com/fjvallarino/monomer-starter) since this issue is not library-specific. The idea of using `ghcid` is primarily a convenience for the programmer, not a feature provided by the library.

Just to be clear: let's keep the issue in this repository since it's easier to track.

**Comment by fjvallarino** [comment] 2022-12-05 13:12
@sproott it's been a really long time, but this PR should handle the feature discussed in this issue: https://github.com/fjvallarino/monomer/pull/239.

The window will be reused when files are saved and `ghcid` reloads the application. You should not need to make any changes for this to work.

Additionally, a way to reuse the latest version of the model between restarts has been added. More details are included in the PR.

To test it, you need to point your `stack.yaml` to:
```yaml
- git: https://github.com/fjvallarino/monomer.git
  commit: 234678ab67cc7da34979e33d76c482ecbd683a0c
```

**Comment by fjvallarino** [comment] 2023-02-24 17:15
The PR has been merged to main; I'll close the issue now.

Please re-open the issue or create a new one if you think something is missing. Thanks

**Closed by fjvallarino** 2023-02-24 17:15 UTC
Labels: question, platform issue
