### ISSUE TITLE
Running monomer-based executables on windows

### ISSUE THREAD

**Issue by ShrykeWindgrace** [fjvallarino/monomer#187] opened 2022-06-28 17:03 UTC
Hi!

Thanks for the great lib, I am looking forward to using it. I especially appreciated setup instructions for windows, they work like a charm.

I tried building your examples (`stack build`), and when I run them via `stack exec -- todo`, I get a separate app window; however, if I run them *without* `stack` - by installing them via `stack install` or by the absolute path inside `.stack-work`, nothing happens. I tried redirecting all streams to the main one, `todo.exe *>&1`, still nothing. What could be missing in this setup? Is there an env variable or config missing somewhere?

System: win10 20h2
```
PS> stack --version
Version 2.7.5, Git revision ba147e6f59b2da75b1beb98b1888cce97f7032b1 x86_64 hpack-0.34.4
```
Main branch of `monomer` at `55ae7f88f1da80064fa3dc6ce6cfb4fce47e8e5a`
```
PS> stack exec -- ghc -V
The Glorious Glasgow Haskell Compilation System, version 8.10.7
```

**Comment by ShrykeWindgrace** [comment] 2022-06-28 17:16
I pulled the latest commit (`51ce06f613eeb5a7e1172ae1a17cf099e053c9cb`), now after a `stack exec -- todo` I get a following modal window:
![image](https://user-images.githubusercontent.com/6421233/176243326-82153935-dc60-4550-8bfd-e6447caf4c42.png)

**Comment by fjvallarino** [comment] 2022-06-28 23:45
Hi @ShrykeWindgrace!

I think the problem is caused by missing .dlls. The setup procedure installs the libraries inside Stack's MingW copy. When you try to run the application outside its sandbox, the application can't find the .dll files. You can use the installer provided by each library (download them from their corresponding sites), but copying the ones from MingW's directory should work too. In the second case, you will most likely want to put the .dll files in the same directory as the executable instead of copying them to a System directory.

To find the location of the installed .dll files, you can run:

```shell
λ stack exec -- where glew32.dll                                                                       
C:\Users\...\AppData\Local\Programs\stack\x86_64-windows\msys2-20210604\mingw64\bin\glew32.dll       
```

I think the required .dlls are:
- glew32.dll
- SDL2.dll
- libfreeglut.dll

---

Thanks for letting me know about the stderr issue! I pushed a branch that catches the exception if logging to stderr fails.

**Comment by fjvallarino** [comment] 2022-08-10 02:29
I'll close the issue for the time being. Please re-open or create a new one if needed. Thanks!

**Closed by fjvallarino** 2022-08-10 02:29 UTC
Labels: question, platform issue

**Comment by ShrykeWindgrace** [comment] 2022-08-10 16:41
Sorry for not reporting my results before going on a vacation; I will test and, if the problem persists, will re-open the issue.
