### ISSUE TITLE
Nix build - SDLCallFailed

### ISSUE THREAD

**Issue by prolic** [fjvallarino/monomer#192] opened 2022-07-09 01:09 UTC
I can successfully build the monomer project using `nix build`. However the resulting binaries have some problems:
```bash
./result/bin/todo 
Invalid window
todo: SDLCallFailed {sdlExceptionCaller = "SDL.Video.glCreateContext", sdlFunction = "SDL_GL_CreateContext", sdlExceptionError = "Invalid window"}
```

**Comment by fjvallarino** [comment] 2022-07-09 01:30
Hi @prolic!

I don't know much about Nix, so I'm probably not the best person to help here (although it's high on my list of things to learn). Looking at a [comment](https://github.com/fjvallarino/monomer/issues/12#issuecomment-902242171) made by @smunix (the contributor of the Nix and GitHub Actions configuration), it seems you should run the applications with a different command:

```bash
nix run .#todo
```
I remember running them successfully in an Ubuntu VM.

**Comment by prolic** [comment] 2022-07-09 02:20
Doesn't seem to work either. Feel free to close this issue if you want to. I'm just struggling myself for over a week to setup nix for my project.

**Comment by fjvallarino** [comment] 2022-07-09 02:27
I think you may need [nixGL](https://github.com/guibou/nixGL). I remember having to use that. It was also mentioned in [this PR](https://github.com/fjvallarino/monomer/pull/13#issuecomment-902529723)

**Comment by fjvallarino** [comment] 2022-07-11 01:21
Just to be sure: have you checked [nixGL](https://github.com/guibou/nixGL)? The error you're getting can probably be fixed by using it.

**Comment by fjvallarino** [comment] 2022-07-18 12:50
I'll close this issue for now. Please re-open if needed. Thanks!

**Closed by fjvallarino** 2022-07-18 12:50 UTC
Labels: question, platform issue

**Comment by exarkun** [comment] 2024-02-12 14:07
> Just to be sure: have you checked [nixGL](https://github.com/guibou/nixGL)? The error you're getting can probably be fixed by using it.

I was seeing this error on a different monomer project on NixOS.  I don't know if I had the same root cause as the original poster but when I ran the app under nixGL instead, the problem went away and the app works.

**Comment by prolic** [comment] 2024-02-14 21:57
I can confirm that nixGL fixes the problem. However I decided to move forward without nix builds. Thanks.
