### ISSUE TITLE
memory leak with Ticker?

### ISSUE THREAD

**Issue by smunix** [fjvallarino/monomer#14] opened 2021-08-19 20:17 UTC
I left Ticker (in the example) running for about 1 hour, it generated about 27GiB of RSS, with 32GiB of swap space depleted. This is on Linux. Will investigate later

**Comment by fjvallarino** [comment] 2021-08-19 20:41
@smunix I can reproduce the issue. I'll investigate it.

**Comment by smunix** [comment] 2021-08-19 21:04
I will look to automate the process of setting up a VM, as you suggested, so we don't have to blow our host stations when these issues occur too.

**Comment by smunix** [comment] 2021-08-21 05:24
I added the VM with #13 and I can see the Linux OOM eventually kills ticker (for taking too much memory) after about 40sec. So this is fairly reproducible and the VM can be used to test the fix.

![vm-oom-killed-ticker](https://user-images.githubusercontent.com/540621/130311489-ffbbd084-4c2a-408c-a340-02c80cfb007d.png)

**Comment by fjvallarino** [comment] 2021-08-21 12:35
@smunix the issue is something broader in the library, not just limited to the ticker example. It's a typical space leak, which I expected to have, although not with such a bad impact.

I've been testing a few things, mostly adding Strict/StrictData pragma in several modules. I could stop the space leak, but it still requires users to add a BangPattern in one argument of buildUI. My next steps are:

- First, I want to avoid requiring the users to add a bang pattern on that function.
- Once that is resolved, I will start reducing the use of Strict/Strict data and replace them with explicit strict fields/bang patterns where needed.

This is going to take me several days to get right.

Once the big issue is solved and a new version published, I will check existing libraries such as [weigh](https://hackage.haskell.org/package/weigh) to see if I can automate these checks. This is not something I plan on doing all at once in a single commit, but progressively over time.

Thanks for reporting this!

**Comment by fjvallarino** [comment] 2021-08-21 14:32
Just in case, I pushed the tests I've been making to a [development branch](https://github.com/fjvallarino/monomer/tree/fix/performance). I will push new changes as soon as I make further progress.

**Comment by fjvallarino** [comment] 2021-08-28 19:48
@smunix I've been testing a few things, mainly adding strictness where it made sense (with help of the profiler).

The biggest issue of memory consumption is solved, although I'll keep looking for further improvements on minor leaks I detected and could not yet fix. If you have a chance to validate, please let me know if the situation also improved for you! I plan on releasing a new version today/tomorrow since even this is still not ideal, it solves the main problem.

I'm going to create a separate issue for the remaining things I want to further investigate.

**Comment by smunix** [comment] 2021-08-28 22:45
Terrific! Resident memory is stable and the VM has been running smoothly.The issue is fixed indeed.

**Comment by fjvallarino** [comment] 2021-09-17 21:48
@smunix I'll close this issue since I think at this point the main problem is solved. If you feel something is missing, please re-open or create a new one.

I'll keep investigating memory usage. I detected in some cases an increase of reported OS resident size, which does not match the maximum resident size reported by GHC's profiler (OS' resident size is much higher than GHC's). This might be related to what's discussed in [this article](https://well-typed.com/blog/2021/01/fragmentation-deeper-look).

Thanks for reporting the issue!

**Closed by fjvallarino** 2021-09-17 21:48 UTC
Labels: bug
