### ISSUE TITLE
Typed keystrokes

### ISSUE THREAD

**Issue by sproott** [fjvallarino/monomer#78] opened 2022-02-09 17:15 UTC
Right now, keystrokes are specified using a String, which I don't think is ideal, because a lot can go wrong. For example, putting in an empty string as a keystroke gives a runtime error after pressing any key and the app crashes: 

```
app: Data.Text.Internal.Fusion.Common.index: Index too large
CallStack (from HasCallStack):
  error, called at libraries/text/src/Data/Text/Internal/Fusion/Common.hs:943:24 in text-1.2.4.1:Data.Text.Internal.Fusion.Common
```

I think it would be better to add a type for defining keystrokes like this:

```hs
data KeyCombination = KeyCombination (Set ModKey) SingleKey

data ModKey = Ctrl | Alt | Shift deriving Eq

data SingleKey = Enter | Tab | ...other functional keys... | CharKey Char
```

 That way the API would be much more typesafe and wouldn't just rely on the correctness of the string.

**Comment by fjvallarino** [comment] 2022-02-10 12:40
Hi @sproott!

I initially tried something similar to what you proposed but chose the string version because of convenience. There were a few reasons, the main ones being:

- The notation is much more compact and easy to read.
- Since the Monomer package is usually imported unqualified, I tried to reduce the number of exported common words. For example, the names of the `nodeKey` and `styleActive` functions were `key` and `active`, but these names caused confusing type errors when creating variables with the same name or forced to use a `hiding` clause in the import statement. I think a few symbols we would be exporting fall in the category of _common words_.
- I felt the programmer would detect invalid strings early.

I'm okay with having an alternative constructor for the widget (maybe `keystrokeT`, for typed) while keeping the current one as it is, but I would keep in mind the names of the exported symbols. Two options for covering this can be:

- Adding some prefix to the symbols we export.
- Putting these symbols in a separate package, not directly exported by Monomer, and have its users import the module explicitly.

An alternative is looking for ways of validating the current input string. Adding this validation was in my plans, but I never got around to it. In this case, the options are:

- Throw an exception when instantiating the widget, indicating as clearly as possible which string has issues (and what the problem is). It is not ideal, but it's good enough to see the error.
- Look for some way of validating the string with TemplateHaskell. This option would be better since it runs at compile time.

**Comment by fjvallarino** [comment] 2022-04-13 04:06
PR https://github.com/fjvallarino/monomer/pull/117 (related to issue https://github.com/fjvallarino/monomer/issues/116) adds logging of invalid key combinations.

I will not pursue the other options, because:

- Exporting all those symbols can cause name clashes and, as I mentioned in other issues, I try to avoid that as much as possible.
- Using TemplateHaskell brings issues of its own.

Considering this, I'm closing this issue.

**Closed by fjvallarino** 2022-04-13 04:06 UTC
Labels: enhancement
