### ISSUE TITLE
Delayed rendering leads to ugly UI

### ISSUE THREAD

**Issue by prolic** [fjvallarino/monomer#173] opened 2022-06-16 00:12 UTC
I attached two video to demonstrate the problem.

The rounded corners `( styleBasic [ radius 4 ] )` are appearing, but very often it takes a second, which is kind of annoying. Not only tooltips are affected, but also buttons.

https://user-images.githubusercontent.com/394428/173962120-ba43ec9a-54c7-4c5c-afd8-84467e427a46.mp4

Here in the second video you can see the same quick flicker for buttons, overlays and close icons.

https://user-images.githubusercontent.com/394428/173962560-f72e92f0-6c1f-4b51-9982-6b2c4ce5f552.mp4

**Comment by fjvallarino** [comment] 2022-06-17 03:41
Do you have a minimal example I can use to reproduce the issue? I tried with the following (it's a modified version of Tutorial 02), but it looks good for me (tested on macOS and Ubuntu 21.04):

```haskell
{-|
Module      : Tutorial02_Styling
Copyright   : (c) 2018 Francisco Vallarino
License     : BSD-3-Clause (see the LICENSE file)
Maintainer  : fjvallarino@gmail.com
Stability   : experimental
Portability : non-portable

Main module for the '02 - Styling' tutorial.
-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TemplateHaskell #-}

module Tutorial02_Styling where

import Control.Lens
import Data.Text (Text)
import Monomer

import qualified Monomer.Lens as L

data AppModel = AppModel {
  _sampleText :: Text,
  _showPicker :: Bool,
  _fontName :: Font,
  _fontSize :: Double,
  _fontColor :: Color,
  _topVisible :: Bool,
  _compVal :: ()
} deriving (Eq, Show)

data AppEvent
  = AppInit
  | AppShow
  | AppHide
  deriving (Eq, Show)

makeLenses 'AppModel

buildComp :: WidgetEnv () () -> () -> WidgetNode () ()
buildComp wenv model = vstack [
    tooltip "Test" (button "AAAA" ())
  ] `styleBasic` [minHeight 100, bgColor gray]

handleComp :: WidgetEnv () () -> WidgetNode () () -> () -> () -> [EventResponse () () AppModel AppEvent]
handleComp wenv node model evt = [
    Report AppHide
  ]

buildUI
  :: WidgetEnv AppModel AppEvent
  -> AppModel
  -> WidgetNode AppModel AppEvent
buildUI wenv model = widgetTree where
  widgetTree = zstack [
      bottomPanel,
      topPanel
        `nodeVisible` (model ^. topVisible)
    ]
  topPanel = composite "" compVal buildComp handleComp

  bottomPanel = vstack [
      titleText "Text",
      box (textField sampleText) `styleBasic` [paddingV 10],

      tooltip "Test" (button "AAAA" AppShow),

      titleText "Font name",
      hgrid [
        hstack [
          labeledRadio "Regular " "Regular" fontName,
          filler
        ],
        hstack [
          labeledRadio "Medium " "Medium" fontName,
          filler
        ],
        hstack [
          labeledRadio "Bold " "Bold" fontName,
          filler
        ],
        hstack [
          labeledRadio "Italic " "Italic" fontName
        ]
      ] `styleBasic` [paddingV 10],

      titleText "Font size",
      hslider fontSize 10 200
        `styleBasic` [paddingV 10, fgColor orange],

      titleText "Font color",
      hstack [
        labeledCheckbox "Show color picker " showPicker,
        filler
      ] `styleBasic` [paddingT 10, paddingB 5],
      colorPicker fontColor
        `nodeVisible` (model ^. showPicker)
        `styleBasic` [paddingB 10],

      sampleTextLabel
    ] `styleBasic` [padding 10]

  titleText text = label text
    `styleBasic` [textFont "Medium", textSize 20]

  sampleTextLabel = label_ (model ^. sampleText) [ellipsis]
    `styleBasic` [
      bgColor dimGray,
      border 4 lightGray,
      radius 10,
      textFont (model ^. fontName),
      textSize (model ^. fontSize),
      textColor (model ^. fontColor),
      textCenter,
      flexHeight 100]

handleEvent
  :: WidgetEnv AppModel AppEvent
  -> WidgetNode AppModel AppEvent
  -> AppModel
  -> AppEvent
  -> [AppEventResponse AppModel AppEvent]
handleEvent wenv node model evt = case evt of
  AppInit -> []
  AppShow -> [Model $ model & topVisible .~ True]
  AppHide -> [Model $ model & topVisible .~ False]

main02 :: IO ()
main02 = do
  startApp model handleEvent buildUI config
  where
    config = [
      appWindowTitle "Tutorial 02 - Styling",
      appWindowIcon "./assets/images/icon.bmp",
      appTheme darkTheme,
      appFontDef "Regular" "./assets/fonts/Roboto-Regular.ttf",
      appFontDef "Medium" "./assets/fonts/Roboto-Medium.ttf",
      appFontDef "Bold" "./assets/fonts/Roboto-Bold.ttf",
      appFontDef "Italic" "./assets/fonts/Roboto-Italic.ttf",
      appInitEvent AppInit
      ]
    model = AppModel {
      _sampleText = "Hello World!",
      _showPicker = False,
      _fontName = "Regular",
      _fontSize = 24,
      _fontColor = white,
      _topVisible = False,
      _compVal = ()
    }
```

**Comment by prolic** [comment] 2022-06-17 04:42
Try to use this as widget within the main UI.

**Comment by fjvallarino** [comment] 2022-06-17 14:25
I'm not sure I follow. The example I pasted has a composite embedded in the main UI and a zstack to simulate what you show in the videos. If possible, could you modify the example and paste it here with your proposed changes?

**Comment by prolic** [comment] 2022-06-17 18:49
That's weird, I can reproduce the issue with your example. See attached video.

https://user-images.githubusercontent.com/394428/174376915-14b2fcd8-39e3-4f04-af43-7c64ff99926a.mp4

**Comment by fjvallarino** [comment] 2022-06-17 19:35
I assume that's Linux. What window manager are you using? I can create VM to test it in the next few days.

**Comment by prolic** [comment] 2022-06-18 03:08
Kubuntu 20.04
KDE Plasma 5.18.8
KDE Frameworks 5.68.0
Qt Version: 5.12.8

**Comment by dimsuz** [comment] 2022-10-18 00:19
By the way, probably related issue happens for me with 100% reproduceability on any widget with rounded corners.

Here's what I see after start:
![image](https://user-images.githubusercontent.com/42920/196306246-38210723-d160-44fa-b889-e0ef64931b06.png)

Not that what's different from OP, for me it _stays this way_ until I move the mouse. And then it immediately becomes this:
![image](https://user-images.githubusercontent.com/42920/196306386-2966d94e-98b4-45bc-8922-3eaecb9281d2.png)

And this is the "style" bit for this widget:

```haskell
    vstack
      [header, diff]
      `styleBasic` [border 1 borderColor, radius 10]
```
`radius 6` looks like this:

![image](https://user-images.githubusercontent.com/42920/196306575-c45d9944-1bbc-4ffb-839e-840c5cae1f21.png)

And sometimes successive launches lead to different artifacts, for example here's the same `radius 6`, but for some reason only right corners are "glitchy":

![image](https://user-images.githubusercontent.com/42920/196306689-2d25ee67-0486-4578-b51d-755bcb6365e5.png)

---

System Details:

**Renderer:** AMD Radeon RX 5500 XT (navi14, LLVM 14.0.6, DRM 3.48, 6.0.1-arch2-1)
**Version:** 4.6 (Core Profile) Mesa 22.2.1
**OS:** ArchLinux, kernel 6.0.1-arch2-1
**Desktop:** GNOME 42.1, Wayland

**Comment by fjvallarino** [comment] 2022-10-21 12:38
I created a PR with a fix/workaround that solves the issue, at least on my end. This seems to be somehow platform dependent, since it does not happen on my older machine (which is the reason I could not work on it earlier): https://github.com/fjvallarino/monomer/pull/215

You can test the fix by modifying your `stack.yaml` to point to:

```yaml
- git: https://github.com/fjvallarino/monomer.git
  commit: 53647710e856da733d69fcf1639976e5824cbb0d
```

**Comment by dimsuz** [comment] 2022-10-21 23:08
I can confirm: with this commit I have no more rounded corners artifacts I described in https://github.com/fjvallarino/monomer/issues/173#issuecomment-1281654946. Nice and clean now! :+1:

**Comment by prolic** [comment] 2022-10-22 00:25
I will try to verify this weekend as well.

**Comment by fjvallarino** [comment] 2022-10-31 11:00
I feel the solution/workaround for https://github.com/fjvallarino/monomer/issues/180 could be something similar to what was done for this issue.

I'll close the issue for the time being, since it appears to work correctly now. If you happen to test it and it does not work as expected, please let me know (re-open the issue or create a new one, as you prefer). Thanks!

**Closed by fjvallarino** 2022-10-31 11:00 UTC
Labels: bug, platform issue
